/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "Drawbar.h"
#include <list>

#define MAIN_MARGIN 20
#define CONTROL_HEIGHT 200

//==============================================================================
/**
*/
class B3synthAudioProcessorEditor  :
	public AudioProcessorEditor,
	private Slider::Listener
{
public:
    B3synthAudioProcessorEditor (B3synthAudioProcessor&);
    ~B3synthAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;

private:	
	Drawbar drawbars[DRAWBAR_COUNT];

	void initDrawbars();
	
	void sliderValueChanged(Slider* slider) override;		

    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    B3synthAudioProcessor& processor;	

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (B3synthAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
